## MongoDB configuration
spring.data.mongodb.database=coronavirus-tracker
spring.data.mongodb.uri="mongodb://localhost/coronavirus-tracker"
spring.data.mongodb.auto-index-creation=false

## Global Statistics (Time Series)
global.stats=https://pomber.github.io/covid19/timeseries.json

## India related data
india.resources=https://api.covid19india.org/resources/resources.json
india.states.stats=https://api.covid19india.org/states_daily.json
india.districts.stats=https://api.covid19india.org/districts_daily.json
india.zones=https://api.covid19india.org/zones.json

google.apiKey=<YourAPI>
google.api = https://maps.googleapis.com/maps/api/geocode/json?key=1234&address=
